<?php

return [
    'irhas-about' => [
        'eyebrow' => 'WELCOME TO IRHAS',
        'title' => 'Crafting Digital Experiences',
        'description' => 'A rationale of few he language continues sign roasted detailed gain, objects out I so the up date defined was of once him, was a read is to our the him, guest editorials.',
        'button_text' => 'Discover More',
        'button_url' => '#',
        'video_url' => 'https://www.youtube.com/watch?v=BsafeSHN_II',
        'video_poster' => 'img/img-video-irhas3.png',
        'secondary_image' => 'img/smartobject4-origin.png',
    ],
    'irhas-portfolio' => [
        'eyebrow' => 'Our Project',
        'title' => 'Completed Projects',
        'description' => 'Trusted rationale with it live stairs is found anyone horrible mild, be to where dreams, live the devious insidious a and be he\'d entered be much sleepiness his the all arches to their dry dressing to over valuable.',
        'button_text' => 'View All Projects',
        'button_url' => '#',
        'items' => [
            [
                'title' => 'Future Program Business',
                'category' => 'Marketing',
                'excerpt' => 'Bed on excessive of alphabet design of our in...',
                'image' => 'img/project-1-irhas3.png',
                'link' => '#',
            ],
            [
                'title' => 'Management Audit Business',
                'category' => 'Additional',
                'excerpt' => 'Bed on excessive of alphabet design of our in...',
                'image' => 'img/project-1-irhas3.png',
                'link' => '#',
            ],
            [
                'title' => 'Corporation Those Investors',
                'category' => 'Additional',
                'excerpt' => 'Bed on excessive of alphabet design of our in...',
                'image' => 'img/project-1-irhas3.png',
                'link' => '#',
            ],
            [
                'title' => 'Limited Liability Company',
                'category' => 'Journey',
                'excerpt' => 'Bed on excessive of alphabet design of our in...',
                'image' => 'img/project-1-irhas3.png',
                'link' => '#',
            ],
        ],
    ],
    'irhas-services' => [
        'eyebrow' => 'Service',
        'title' => 'What We Can Do',
        'description' => 'Ever starting it the them it caught parameters ever would as to thousands consider sentences gradual great studies the in and each enough state immense is.',
        'button_text' => 'View all service',
        'button_url' => '/services',
        'items' => [
            [
                'title' => 'Referral Service Management',
                'category' => 'government',
                'image' => 'img/service-3-irhas3.png',
                'link' => '/services/referral-service-management',
            ],
            [
                'title' => 'Personal Service Development',
                'category' => 'creative',
                'image' => 'img/service-3-irhas3.png',
                'link' => '/services/personal-service-development',
            ],
            [
                'title' => 'Strategy Business Management',
                'category' => 'creative',
                'image' => 'img/service-3-irhas3.png',
                'link' => '/services/strategy-business-management',
            ],
            [
                'title' => 'Partnership Quality Member',
                'category' => 'adversitising',
                'image' => 'img/service-3-irhas3.png',
                'link' => '/services/partnership-quality-member',
            ],
        ],
    ],
    'irhas-testimonial' => [
        'eyebrow' => 'Testimonial',
        'title' => 'What Our Clients Say.',
        'title_mobile' => 'What Our Client Says',
        'description' => 'Ever starting it the them it caught parameters ever would as to thousands consider sentences gradual great studies the in and each enough state immense is.',
        'button_text' => 'Contact Us',
        'button_url' => '#',
        'side_image' => 'img/smartobject5.png',
        'items' => [
            [
                'author' => 'Winston Churchill',
                'job' => 'Client',
                'quote' => 'Particularly to tone on the are seen, cheerful, you him this period, have to to audience.',
            ],
            [
                'author' => 'Richard Bronson',
                'job' => 'Client',
                'quote' => 'Particularly to tone on the are seen, cheerful, you him this period, have to to audience.',
            ],
        ],
    ],
    'irhas-counter' => [
        'items' => [
            [
                'prefix' => '',
                'suffix' => '',
                'number' => '129847',
                'label' => 'Clients from 60 Countries',
            ],
            [
                'prefix' => '$',
                'suffix' => '',
                'number' => '796882',
                'label' => 'in Average Saving',
            ],
            [
                'prefix' => '',
                'suffix' => '%',
                'number' => '89',
                'label' => 'Client Recommend',
            ],
        ],
    ],
    'irhas-blog' => [
        'eyebrow' => 'Our Blog',
        'title' => 'Latest News',
        'posts_limit' => '4',
        'view_all_text' => 'View All Posts',
        'view_all_url' => '/blog',
    ],
    'irhas-blog-list' => [],
    'irhas-services-list' => [
        'default_card_image' => 'img/service-1-service-page-irhas-3.png',
        'contact_title' => 'We have 24 years experience in Digital Agency',
        'contact_description' => 'Have just introduced pane, go when or over were this the it human who assignment. To concepts.',
        'contact_button_text' => 'Contact Us',
        'contact_button_url' => '/contact',
    ],
    'irhas-page-banner' => [
        'eyebrow' => 'Service',
        'title' => 'What We Have.',
        'background_image' => 'img/banner-header-service.png',
    ],
    'irhas-contact' => [
        'eyebrow' => 'Contact Us',
        'title' => 'Get in touch',
        'map_embed_url' => 'https://maps.google.com/maps?q=London%20Eye%2C%20London%2C%20United%20Kingdom&t=m&z=18&output=embed&iwloc=near',
        'weekday_hours' => 'MON-FRI 09:00 – 19:00',
        'weekend_hours' => 'SAT-SUN 10:00 – 14:00',
        'submit_button_text' => 'Send Message',
    ],
    'irhas2-hero' => [
        'eyebrow' => 'Welcome To Irhas',
        'title' => 'Crafting Digital Experiences',
        'description' => 'ransmitting expand quite was success make ocean. As little did even in and forest the as it to of to we\'ve that on or unrecognisable. Even the are right activity should, effort from details much systems led house. Admittance.',
        'button_text' => 'Discover More',
        'button_url' => '#',
        'background_image' => 'img/hero-image.png',
    ],
    'irhas2-features' => [
        'eyebrow' => 'Welcome To Irhas',
        'title' => 'what we have',
        'description' => 'Rendering of children purer himself safely the what proposal come omens, ever can a something at could and forth. Long and the at away to ruining the cons.',
        'items' => [
            ['title' => 'Multiple Concept', 'excerpt' => 'Back have focuses merit of by but that him it with worthy down this to about able like greediness absolutely samples else', 'image' => 'img/img-home-gif-1.png'],
            ['title' => 'Perfect Code Like a Niche', 'excerpt' => 'Minutes. Attained brief. The of human I in that too out small many not contribution had the them. Over be last goals the her into like told two.', 'image' => 'img/img-home-gif-1.png'],
            ['title' => 'Multi Language Theme', 'excerpt' => 'My about proportion if even the evening separated post I area transactions to wouldn\'t many advised day twice play', 'image' => 'img/img-home-gif-1.png'],
        ],
    ],
    'irhas2-portfolio' => [
        'eyebrow' => 'Our Projects',
        'title' => 'Completed Projects',
        'description' => 'She cold the writer many the in safely to funny travelling to years for funds of front up free and in even its may afloat.',
        'button_text' => 'View All Projects',
        'button_url' => '#',
        'read_more_text' => 'Learn More',
        'items' => [
            ['title' => 'Future Program Business', 'category' => 'marketing', 'excerpt' => 'There their hazardous because a proportion the that note...', 'image' => 'img/img-project-irhas2.png', 'link' => '#'],
            ['title' => 'Management Audit Business', 'category' => 'additional', 'excerpt' => 'To in the well rationale sat the destruction. The...', 'image' => 'img/img-project-irhas2.png', 'link' => '#'],
            ['title' => 'Corporation Those Investors', 'category' => 'additional', 'excerpt' => 'Approved tone think good stitching down of concepts we\'ve...', 'image' => 'img/img-project-irhas2.png', 'link' => '#'],
            ['title' => 'Limited Liability Company', 'category' => 'journey', 'excerpt' => 'Made so attention flatter were is he boss the...', 'image' => 'img/img-project-irhas2.png', 'link' => '#'],
        ],
    ],
    'irhas2-about-video' => [
        'eyebrow' => 'Since 2008',
        'title' => 'We\'re a creative branding and communications company of creative thinkers,',
        'quote' => 'Derived we but in who muff policeman, family building and would if concept turn pretty its perfected',
        'description' => 'In have seven relays little mechanic. For should world; Encourage like the derisively how range writers.',
        'video_url' => 'https://www.youtube.com/watch?v=BsafeSHN_II',
        'video_poster' => 'img/img-video-irhas-2.png',
        'secondary_image' => 'img/smartobject.png',
    ],
    'irhas2-team' => [
        'eyebrow' => 'Meet The Team',
        'title' => 'Our Best People',
        'description' => 'something to and a accordingly the real subject more long answer distance devious get stands conduct, continued reasoning of still spends completely our researches his want beginning failures it particular mellower tone.',
        'button_text' => 'Meet All People',
        'button_url' => '#',
        'items' => [
            ['name' => 'Michel Groch', 'role' => 'Director', 'image' => 'img/img-team-1- irhas2.png', 'facebook' => '#', 'twitter' => '#', 'linkedin' => '#'],
            ['name' => 'Adel Kovacs', 'role' => 'Operations manager', 'image' => 'img/img-team-1- irhas2.png', 'facebook' => '#', 'twitter' => '#', 'linkedin' => '#'],
            ['name' => 'Joseph George', 'role' => 'Senior Leasing Executive', 'image' => 'img/img-team-1- irhas2.png', 'facebook' => '#', 'twitter' => '#', 'linkedin' => '#'],
            ['name' => 'Michelle McCoy', 'role' => 'Leasing Executive', 'image' => 'img/img-team-1- irhas2.png', 'facebook' => '#', 'twitter' => '#', 'linkedin' => '#'],
        ],
    ],
    'irhas2-testimonial' => [
        'eyebrow' => 'Testimonial',
        'title' => 'What Our Clients Say.',
        'items' => [
            ['quote' => 'Starting of owner me dressing forest step arduous a what\'s most a from can to farther are', 'author' => 'Adam Lancaster', 'job' => 'Global L&D Partner, TVC Marketing', 'logo' => 'img/testimonial-img-logo-1.png'],
            ['quote' => 'Thing live safe one mountains, would, aged get your better retired, cache doctor when and build quite', 'author' => 'Adam Lancaster', 'job' => 'Global L&D Partner, TVC Marketing', 'logo' => 'img/testimonial-img-logo-1.png'],
            ['quote' => 'create the home, as more to and, may particular, right which of respond taken was stupid circles with to concepts', 'author' => 'Adam Lancaster', 'job' => 'Global L&D Partner, TVC Marketing', 'logo' => 'img/testimonial-img-logo-1.png'],
        ],
    ],
    'irhas2-blog' => [
        'eyebrow' => 'Our Blog',
        'title' => 'Latest News',
        'posts_limit' => '3',
        'default_image' => 'img/img-latest-news-1-irhas-2.png',
    ],
];
