<?php

return [
    'new-design-hero' => [
        'background_image_url' => 'https://clean-air.ae/uploads/banner-area-background.png',
        'mobile_background_image_url' => 'https://clean-air.ae/uploads/hero-banner-mobile.jpeg',
        'background_image_source' => 'url',
        'title' => "Breathe\nCleaner Air\nin Your Home",
        'subtitle' => 'AC DEEP CLEANING ACROSS DUBAI',
        'button_text' => 'Request a Quote',
        'button_url' => '#',
        'features' => [
            ['icon' => '🛡️', 'text' => 'Remove Dust, Mold & Allergens'],
            ['icon' => '💨', 'text' => 'Improve Cooling Performance'],
            ['icon' => '⚡', 'text' => 'Lower Electricity Consumption'],
            ['icon' => '🏆', 'text' => 'NADCA Accredited Specialists'],
        ],
    ],
    'new-design-promise' => [
        'background_image_url' => 'https://clean-air.ae/uploads/about-us-bg.png',
        'background_image_source' => 'url',
        'eyebrow' => 'ABOUT US',
        'title' => "Dubai's Trusted\nAC Cleaning Experts",
        'paragraph_1' => 'At Clean Air, we specialize in professional AC deep cleaning services that help you breathe cleaner, healthier air and improve your system\'s performance.',
        'paragraph_2' => 'Our mission is simple — provide top-quality service with honesty, transparency, and care for every home and business we serve.',
        'features' => [
            ['icon' => '💨', 'title' => "NADCA\nAccredited", 'text' => 'Trained, skilled, and dedicated to delivering excellence.'],
            ['icon' => '💰', 'title' => 'Experienced Professionals', 'text' => 'Trained, skilled, and dedicated to delivering excellence.'],
            ['icon' => '⭐', 'title' => "Healthier\nLiving", 'text' => 'Cleaner air, fewer allergens, and a healthier environment.'],
            ['icon' => '😊', 'title' => "Customer\nFocused", 'text' => 'Your satisfaction is our priority — every time.'],
        ],
        'card_image_url' => 'https://clean-air.ae/uploads/clean-air-promise-logo.png',
        'card_title' => 'Cleaner Air. Better Health. Lower Bills.',
        'card_text' => 'We help your AC run better, so you can live better.',
        'features_2' => [
            ['icon' => '💨', 'title' => 'High Quality Service', 'text' => 'Premium cleaning with attention to detail.'],
            ['icon' => '💰', 'title' => 'Happy Customers', 'text' => 'Our growing community trusts us for reliable service.'],
            ['icon' => '⭐', 'title' => 'Reliable & On Time', 'text' => 'We respect your time and always deliver as promised.'],
        ],
    ],
    'new-design-difference' => [
        'eyebrow' => 'SEE THE DIFFERENCE',
        'title' => "From Dirty AC to\nFresh Clean Air",
        'description' => 'Dust, mold, and bacteria build up in your AC over time, reducing efficiency and affecting the air you breathe. Our deep cleaning service restores peak performance and brings fresh, clean air back into your home.',
        'features' => [
            ['icon' => '🛡️', 'text' => 'Remove dust, mold & allergens'],
            ['icon' => '💨', 'text' => 'Improve cooling performance'],
            ['icon' => '⚡', 'text' => 'Lower energy consumption'],
        ],
        'before_image_url' => 'https://clean-air.ae/uploads/ac-before.png',
        'after_image_url' => 'https://clean-air.ae/uploads/ac-after.png',
    ],
    'new-design-included' => [
        'eyebrow' => "WHAT'S INCLUDED",
        'title' => 'Complete AC Deep Cleaning Service',
        'items' => [
            ['icon' => '🌀', 'title' => 'Coil Cleaning', 'text' => 'Remove dirt and buildup from evaporator coils for better cooling.'],
            ['icon' => '💨', 'title' => 'Duct Inspection', 'text' => 'Inspect ducts for dust, mold, and blockages.'],
            ['icon' => '🧽', 'title' => 'Filter Deep Cleaning', 'text' => 'Deep clean or replace filters to improve air quality.'],
            ['icon' => '☀️', 'title' => 'Mold Treatment', 'text' => 'Eliminate mold and bacteria from critical components.'],
            ['icon' => '🛡️', 'title' => 'Sanitization', 'text' => 'Sanitize the unit for healthier indoor air.'],
            ['icon' => '✅', 'title' => 'Final Testing', 'text' => 'Test performance to ensure optimal cooling.'],
        ],
    ],
    'new-design-process' => [
        'eyebrow' => 'OUR PROCESS',
        'title' => 'Thorough. Safe. Effective.',
        'description' => 'We follow a detailed deep cleaning process to ensure your AC performs at its best and the air in your home stays clean and fresh.',
        'button_text' => 'Request a Quote',
        'button_url' => '#',
        'steps' => [
            ['number' => '01', 'icon' => '📋', 'title' => 'Inspection', 'text' => 'We inspect your AC unit to check for dust, mold and blockages.'],
            ['number' => '02', 'icon' => '🧴', 'title' => 'Deep Cleaning', 'text' => 'We remove dirt, clean filters, coils and all internal components.'],
            ['number' => '03', 'icon' => '🛡️', 'title' => 'Sanitizing', 'text' => 'We sanitize the unit to eliminate bacteria, mold and allergens.'],
            ['number' => '04', 'icon' => '💨', 'title' => 'Final Check', 'text' => 'We test performance to ensure your AC runs like new.', 'last' => true],
        ],
    ],
    'new-design-results' => [
        'eyebrow' => 'REAL RESULTS',
        'title' => 'Trusted by Homes Across Dubai',
        'slides' => [
            ['location' => 'Dubai Marina', 'before_image_url' => 'https://clean-air.ae/uploads/ac-before.png', 'after_image_url' => 'https://clean-air.ae/uploads/ac-after.png', 'review' => 'Our AC wasn\'t cooling properly and had a bad smell. After Clean Air\'s deep cleaning service, the airflow improved immediately and the whole house feels fresher.', 'name' => 'Sarah M.'],
            ['location' => 'Jumeirah', 'before_image_url' => 'https://clean-air.ae/uploads/ac-before.png', 'after_image_url' => 'https://clean-air.ae/uploads/ac-after.png', 'review' => 'Professional team, on time, and very thorough. Highly recommend Clean Air for AC deep cleaning.', 'name' => 'Ahmed K.'],
            ['location' => 'Business Bay', 'before_image_url' => 'https://clean-air.ae/uploads/ac-before.png', 'after_image_url' => 'https://clean-air.ae/uploads/ac-after.png', 'review' => 'Great service and noticeable difference in air quality after the cleaning.', 'name' => 'Lisa R.'],
        ],
    ],
    'new-design-breathe' => [
        'background_image_url' => 'https://clean-air.ae/uploads/banner-area-background.png',
        'background_image_source' => 'url',
        'eyebrow' => 'BREATHE CLEANER. LIVE BETTER',
        'title' => "Ready to Breathe\nCleaner Air?",
        'description' => 'Book your AC deep cleaning today and enjoy fresher air, better cooling, and peace of mind.',
        'button_text' => 'Request a Quote',
        'button_url' => '#',
    ],
    'new-design-nadca' => [
        'background_image_url' => 'https://clean-air.ae/uploads/nadaca-background.png',
        'background_image_source' => 'url',
        'eyebrow' => 'NADCA APPROVED',
        'title' => "Certified. Trusted.\nIndustry Approved.",
        'description' => 'We follow NADCA standards to deliver the highest level of air duct cleaning in Dubai.',
        'logo_image_url' => 'https://clean-air.ae/uploads/nadaca-logo.png',
        'card_text' => 'Clean Air is a NADCA accredited company committed to delivering professional AC duct cleaning services that meet international standards for safety, hygiene and HVAC system performance.',
        'features' => [
            ['icon' => '🛡️', 'title' => 'NADCA Standards', 'text' => 'We follow strict NADCA guidelines and industry best practices for every AC cleaning project.'],
            ['icon' => '⚙️', 'title' => 'Advanced Equipment', 'text' => 'Industry-leading equipment ensures deeper, safer and more effective cleaning results.'],
            ['icon' => '👨‍🔧', 'title' => 'Certified Technicians', 'text' => 'Our trained specialists deliver consistent, high-quality results every time.'],
            ['icon' => '🎓', 'title' => 'Certified Professionals', 'text' => 'Experienced technicians trained to deliver reliable and professional AC cleaning services.'],
            ['icon' => '👨‍👩‍👧', 'title' => 'Better Air Quality', 'text' => 'Enjoy healthier indoor air, reduced allergens and improved AC performance all year round.'],
        ],
    ],
    'new-design-areas' => [
        'background_image_url' => 'https://clean-air.ae/uploads/nadaca-background.png',
        'background_image_source' => 'url',
        'eyebrow' => 'SERVICE AREAS',
        'title' => "Proudly Serving\nAcross Dubai",
        'description' => 'We provide professional AC deep cleaning services across all major areas in Dubai.',
        'van_image_url' => 'https://clean-air.ae/uploads/van.png',
        'phone' => '+971542140166',
        'phone_label' => 'Available 7 Days a Week',
        'whatsapp' => '+971542140166',
        'whatsapp_label' => 'Quick Response',
        'locations' => [
            ['key' => 'downtown', 'name' => 'Downtown Dubai'],
            ['key' => 'marina', 'name' => 'Dubai Marina'],
            ['key' => 'jumeirah', 'name' => 'Jumeirah'],
            ['key' => 'businessbay', 'name' => 'Business Bay'],
            ['key' => 'arabian', 'name' => 'Arabian Ranches'],
            ['key' => 'palm', 'name' => 'Palm Jumeirah'],
            ['key' => 'jvc', 'name' => 'JVC (Jumeirah Village Circle)'],
            ['key' => 'mirdif', 'name' => 'Mirdif'],
            ['key' => 'barsha', 'name' => 'Al Barsha'],
        ],
    ],
    'new-design-pricing' => [
        'background_image_url' => 'https://clean-air.ae/uploads/nadaca-background.png',
        'background_image_source' => 'url',
        'eyebrow' => 'PRICING',
        'title' => 'Transparent Pricing',
        'subtitle' => 'Simple. Fair. Professional.',
        'description' => 'Premium AC deep cleaning services with honest pricing and no hidden charges.',
    ],
    'new-design-quote' => [
        'background_image_url' => 'https://clean-air.ae/uploads/nadaca-background.png',
        'background_image_source' => 'url',
        'eyebrow' => 'GET YOUR PERSONALIZED QUOTE',
        'title' => 'Request a Quote',
        'description' => 'Fill out the form and our specialists will get back to you with a tailored quote for your property.',
        'badge_image_url' => 'https://clean-air.ae/uploads/Nadca-logo-2.png',
    ],
    'new-design-privacy-hero' => [
        'background_image_url' => 'https://clean-air.ae/uploads/banner-area-background.png',
        'background_image_source' => 'url',
        'title' => 'Privacy Policy',
        'updated_text' => 'Last Updated: June 2026',
        'description' => 'At Clean Air by Renovation Hub ("Clean Air", "we", "our", or "us"), we respect your privacy and are committed to protecting your personal information.',
    ],
    'new-design-privacy-content' => [
        'blocks' => [],
    ],
];
